### PR TITLE
add macagua like a Plone Trainer

### PR DESCRIPTION
**Pull request by macagua**

### CODE REVIEW

**Comment by macagua** [comment]
@svx you can check out this pull request, if it is ok, please merge it?

**Comment by svx** [comment]
@macagua You added too much :)

Currently we 'only' use:

```
avatar:
github:
```

The other ones are not supported yet :)

Can you shorten 'position' ?

For the current template the description is too long and will look not that nice.

I apologize but the theme is not 'done' yet, this was 'hacked' together to have it up and running for the conference, but the trade-off  is that some it is not 100% ready yet.

**Comment by macagua** [comment]
@svx ok let me check it :-)

**Comment by macagua** [comment]
@svx it done! :+1: 

please you can recheck out this pull request, if it is ok, please merge it?

Thanks :-)

**Comment by jensens** [comment]
since I do not like green non-merged/open PRs in the list and this one is ready after @macagua changes -> merge.

**Comment by macagua** [comment]
@jensens thanks you!!!

**Pull request merged**
