### PR TITLE
Add a Gitter chat badge to README.rst

### PR DESCRIPTION
**Pull request by gitter-badger**
### plone/training.plone.org now has a Chat Room on Gitter

@MrTango has just created a chat room. You can visit it here: [https://gitter.im/plone/training.plone.org](https://gitter.im/plone/training.plone.org?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&content=body_link).

This pull-request adds this badge to your README.rst:

[Gitter](https://gitter.im/plone/training.plone.org?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=body_badge)

If my aim is a little off, please [let me know](https://github.com/gitterHQ/readme-badger/issues).

Happy chatting.

PS: [Click here](https://gitter.im/settings/badger/opt-out) if you would prefer not to receive automatic pull-requests from Gitter in future.

### CODE REVIEW

**Comment by svx** [comment]
@MrTango is meant for here [static landing page] repository or for the training itself ? :)

**Review by MrTango — APPROVED** [review]

**Comment by MrTango** [comment]
@svx no it's just for the README.rst you see on github.

**Comment by MrTango** [comment]
I'll close this and add the bage by my self, to resolve the contributor check.

**Comment by svx** [comment]
@MrTango yes but for which repo ? :) 

Please note that the current README of this repo, will change a lot in a couple of hours, maybe you meant to add this to:  https://github.com/plone/training ? Which is **the** repo of the training. :)

**Pull request closed without merging**
